name: CICD

on: 
  push:
    branches:
      - main_aws
jobs:
  build-and-deploy:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install Dependendcies
        run: npm install
      - name: Generate Deployment Packages
        run: zip -r nodejs-app-build.zip .
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: NcMediaManagementAppBE
          environment_name: NcMediaManagementAppBE-env
          version_label: ${{github.sha}}
          region: ap-south-1
          deployment_package: nodejs-app-build.zip
