name: Deploy to EC2

on:
  push:
    branches:
      - main_v3

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws_region: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: SSH and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Deploying to path: $(pwd)"
            cd /home/ec2-user/projects/ncMediaManagementAppBE
            echo "Current directory: $(pwd)"
            git config pull.rebase false
            git checkout -- package-lock.json
            git pull origin main_v3
            echo "Installing dependencies..."
            npm install --production
            echo "Setting up environment variables..."
            cat > .env << EOF
            BUCKET_REGION=${{ secrets.AWS_REGION }}
            ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY_ID }}
            SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            HEX_KEY_ENCRYPT_DECRYPT=${{ secrets.HEX_KEY_ENCRYPT_DECRYPT }}
            BUCKET_NAME_ARTICLE=${{ secrets.BUCKET_NAME_ARTICLE }}
            BUCKET_NAME_EMPLOYEE_DOCS=${{ secrets.BUCKET_NAME_EMPLOYEE_DOCS }}
            BUCKET_NEWS_FRAME=${{ secrets.BUCKET_NEWS_FRAME }}
            MONGO_DB_URL=${{ secrets.MONGO_DB_URL }}
            EMAIL_USER=${{ secrets.EMAIL_USER }}
            EMAIL_PASS=${{ secrets.EMAIL_PASS }}
            EMAIL_GRIEVANCE_USER=${{ secrets.EMAIL_GRIEVANCE_USER }}
            EMAIL_GRIEVANCE_PASSWORD=${{ secrets.EMAIL_GRIEVANCE_PASSWORD }}
            FIREBASE_SDK_JSON=${{ secrets.FIREBASE_SDK_JSON }}
            NODE_ENV=production
            EOF
            echo "Environment variables set. Restarting PM2..."
            pm2 restart all
