name: Node.js CI

on:
  push:
    branches: [ "main_aws_karthik" ]

jobs:
  build:

    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [ 18.16.0 ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    # BELOW COMMANDS IS TRAIL TO UPDATE CODE WITHOUT .env
      # with:
      #   fetch-depth: 0  # Ensures full history is fetched so that .env is not overwritten
    # - name: Restore .env file
    #   run: git checkout HEAD^ .env  # Restore the .env file to its previous state
    # AOBE COMMANDS IS TRAIL TO UPDATE CODE WITHOUT .env

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci --force
    - run: npm run build --if-present
    - run: pm2 restart index.js
